### ISSUE TITLE
error depois da senha

### ISSUE THREAD

**Issue by malvsz** [izmcm/BBBot#17]
depois que eu coloco a senha ta dando esse erro.

Traceback (most recent call last):
  File "script.py", line 27, in <module>
    browser = webdriver.Chrome(capabilities=caps)
TypeError: __init__() got an unexpected keyword argument 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 32, in <module>
    browser = webdriver.Firefox(capabilities=caps)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver'

**Comment by erickssa** [comment]
tbm

**Comment by fabiomurilo121** [comment]
Tente executar direto no terminal e veja se você instalou o geckodrive para o firefox, o link do repositório é para mac, tem que mudar para o sistema que você esta usando.
