### ISSUE TITLE
Erro após primeiro voto computado

### ISSUE THREAD

**Issue by antonioanerao** [izmcm/BBBot#21]
De todas as vezes que eu tentei votar, apenas uma conseguiu computar um segundo voto. Segue o erro:

Traceback (most recent call last):
  File "script.py", line 184, in <module>
    ac.move_to_element(captcha).move_by_offset(posX, posY).click().perform()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (633, 934.5416564941406) is out of bounds of viewport width (1280) and height (933)

Alguém tem alguma ideia de como resolver?
O problema ocorreu no meu ubuntu, kali e no windows 10

**Comment by rammonfelip** [comment]
Acontecendo o mesmo comigo. Só computa o primeiro voto

**Comment by izmcm** [comment]
Isso ta rolando porque o lugar do clique ta fora da tela visível. Consertei deixando a janela automaticamente mais estreita e para forçar a responsividade do site deixar tudo visível! Commit aa15f8d22b9170c8d342d8f71611109a9ddf273a
