### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by harmogit** [izmcm/BBBot#8]
o meu está dando o seguinte erro:

Felipe é o botao 0
procurando por calendário
erro - captcha não encontrado
Felipe é o botao 0
procurando por comida japonesa
salvando
a imagem se encontra nos pontos: 138.5 X 30.5
o tamanho do captcha é 269.0 X 57.0
Traceback (most recent call last):
  File "C:\Users\pc\Documents\BBBot-master\script.py", line 120, in <module>
    ac.move_to_element(captcha).move_by_offset(posX, posY).click().perform()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (674, 746) is out of bounds of viewport width (1366) and height (693)

como posso arrumar?

**Comment by linkgab** [comment]
Modifica o tamanho da sua resolução.
Também pode ser o tamanho da janela do navegador, você pode usar o driver.set_window_size(x, y) ou o window.scroll() para rolar a tela para baixo e o index não ficar out of range.

**Comment by cleivson** [comment]
É, acho que o @MiniMarvin corrigiu isso em outra issue, mas maximimar o navegador geralmente ajuda.

**Comment by MiniMarvin** [comment]
corrigido
